apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-vpcblock-odf-general
provisioner: vpc.block.csi.ibm.io
parameters:
  profile: "general-purpose"        # The VPC Storage profile used. https://cloud.ibm.com/docs/vpc?topic=vpc-block-storage-profiles&interface=ui#tiers-beta
  csi.storage.k8s.io/fstype: "ext4" # ext4 is the default filesytem used. The user can override this default
  billingType: "hourly"             # The default billing policy used. The uer can override this default
  encrypted: "false"                # By default, all PVC using this class will only be provider managed encrypted. The user can override this default
  encryptionKey: ""                 # If encrypted is true, then a user must specify the encryption key used assocatied KP instance
  resourceGroup: ""                 # Use resource group if specified here. else use the one mentioned in storage-secrete-store
  region: ""
  zone: ""                          # By default, the storage vpc driver will select a zone. The user can override this default
  tags: ""                          # A list of tags "a, b, c" that will be created when the volume is created. This can be overidden by user
  classVersion: "1"
reclaimPolicy: "Delete"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
